organization: CUNY Graduate Center
location:
  city: New York
  state: NY
event: Digital Humanities Research Infrastructure For Teaching
intro: "The Digital Humanities Research Institute (DHRI) is an intensive, community-oriented, 
and foundational approach to learning technical skills in service of humanities teaching and 
learning. The DHRI curriculum features workshops, tutorials, glossaries, resources, reading 
materials, and more that have been developed at The Graduate Center, City University of New York 
since 2016.

Part of a 2019 grant from the National Endowment for the Humanities' (NEH) Office of 
Digital Humanities (ODH), DHRI's curriculum, which was originally developed for in-person workshops, 
was revised in Summer 2020 to better meet the needs of virtual instruction due to the covid-19 pandemic. 
While the curriculum has always been available openly on GitHub, this site creates a more 
user-friendly and functional interface that is open and free for public use."
slideout: 
  enabled: true
  language: python
schedule:
  - date: 2020-09-14
    time: 9:00am
    title: "Welcome to the DHRI"
    description: "This is the first day of the DHRI. We will introduce ourselves and the DHRI, 
    and discuss the goals of the institute."
    presenters:
      - name: "Dr. Matthew K. Gold"
        title: "Director, Digital Humanities Research Institute"
        image: "mkgold.jpg"
        bio: "Matthew K. Gold is an Associate Professor of English at the Graduate Center, 
        City University of New York. He is the Director of the Digital Humanities Research Institute 
        (DHRI) and the Director of the Digital Humanities Initiative at the Graduate Center. 
        He is the author of The Digital Humanities and the Future of Literary Studies (2017) 
        and The Digital Humanities: A Primer for Students and Scholars (2014)."
        twitter: "https://twitter.com/mkgold"
        github: ""
      - name: "Dr Lisa Rhody"
        title: "Director, Digital Humanities Initiative"
        image: "lrhody.jpg"
        bio: "Lisa Rhody is an Associate Professor of English at the Graduate Center, City 
        University of New York. She is the Director of the Digital Humanities Initiative at the 
        Graduate Center. She is the author of The Digital Humanities: A Primer for Students and 
        Scholars (2014) and co-editor of The Digital Humanities: A Reader (2017)."
        twitter: "https://twitter.com/lisarhody"
        github: ""
  - date: 2020-09-15
    time: 9:00am
    title: "Introduction to the Command Line"
    description: "This workshop will introduce the command line, a text-based interface for 
    interacting with your computer. We will cover basic commands, file navigation, and 
    permissions."
    presenters:
      - name: "Stephen Zweibel"
        title: "Digital Scholarship Librarian"
        image: "szweibel.jpg"
        bio: "Stephen Zweibel is the Digital Scholarship Librarian at the Graduate Center,
        City University of New York. He is the author of The Digital Humanities: A Primer for
        Students and Scholars (2014) and co-editor of The Digital Humanities: A Reader (2017)."
        twitter: "https://twitter.com/stephenzweibel"
        github: ""
