organization: CUNY Graduate Center
location:
  city: New York
  state: NY
event: "The JavaScripting Master's Student"
motto: "By Zach Lloyd & Stephen Zweibel"
intro: "This is a basic introduction to JavaScript, which is the programming language of the web. The class is designed for anyone interested in developing a website, or creating an interactive data visualization. By the end of this course, you will be able to read JavaScript you find online and adapt it to your needs. You will also have an opportunity to work with common JavaScript libraries/tools and enhance your own research practices."
slideout: 
  enabled: false
  language: javascript
presentation: false
