organization: CUNY Graduate Center
location:
  city: New York
  state: NY
event: Digital Humanities Research Infrastructure For Teaching
intro: "The Digital Humanities Research Institute (DHRI) is an intensive, community-oriented, 
and foundational approach to learning technical skills in service of humanities teaching and 
learning. The DHRI curriculum features workshops, tutorials, glossaries, resources, reading 
materials, and more that have been developed at The Graduate Center, City University of New York 
since 2016.

Part of a 2019 grant from the National Endowment for the Humanities' (NEH) Office of 
Digital Humanities (ODH), DHRI's curriculum, which was originally developed for in-person workshops, 
was revised in Summer 2020 to better meet the needs of virtual instruction due to the covid-19 pandemic. 
While the curriculum has always been available openly on GitHub, this site creates a more 
user-friendly and functional interface that is open and free for public use."
slideout: 
  enabled: true
  language: python
schedule:
  - date: 2023-03-02
    time: 9:00am
    title: "Welcome to the DHRI"
    description: "This is the first day of the DHRI. We will introduce ourselves and the DHRI, 
    and discuss the goals of the institute."
  - date: 2023-03-02
    time: 11:00am
    title: "Introduction to the Command Line"
    description: "This workshop will introduce you to the command line, a text-based interface 
    for interacting with your computer. We will cover basic commands, file management, and 
    navigating the file system."
  - date: 2023-03-04
    time: 9:00am
    title: "Introduction to Git and GitHub"
    description: "This workshop will introduce you to Git and GitHub, a version control system 
    and a web-based hosting service for software development projects.